[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dimensions.columns = 200
dimensions.lines = 50
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal.family = "Inconsolata Nerd Font"
size = 20
