
[window]
opacity = 0.95
blur = true
padding.x = 10
padding.y = 10

[font]
normal.family = "MapleMono NF"
bold.family = "MapleMono NF" 
italic.family = "MapleMono NF" 
bold_italic.family = "MapleMono NF" 

size = 12.0

[general]
import = ["~/.config/alacritty/rose-pine.toml"]
